tunnel: <tunnel uuid>
credentials-file: /home/server/.cloudflared/<tunnel uuid>.json

ingress:
  - hostname: aryadee.dev
    service: https://localhost:443
    originServerName: aryadee.dev
  - hostname: nathaliektherapy.com
    service: https://localhost:443
    originServerName: nathaliektherapy.com
  - service: http_status:404
